name: Vault Key/Value
description: Export secrets from Hashicorp Vault (Key/Value Secret Engine) as environment variables.
author: https://adabay.rocks
configuration:
  properties:
    secrets:
      type: array
    secret_path:
      type: string
    secret_key:
      type: string
    exported_env_variable_name:
      type: string
